name: Heroku Deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  Cache: 'npm'
  CacheDependencyPath: 'package-lock.json'

jobs:
  build-and-test-node:
    name: Build Node
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        node-version: [ 18.x ]
        environment:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "${{ env.Cache }}"
          cache-dependency-path: "${{ env.CacheDependencyPath }}"

      - name: Print current node version
        run: node -v

      - name: Print current npm version
        run: npm -v

      - name: Restore Npm Packages
        run: npm ci

      - name: Node build
        run: CI=false npm run build --if-present --production

  heroku-deploy:
    needs: [ build-and-test-node ]
    name: Heroku Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        env:
          HD_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          HD_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
          HD_FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}}
          HD_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          HD_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
          HD_FIREBASE_SENDER_ID: ${{secrets.FIREBASE_SENDER_ID}}
          HD_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
          HD_AUTH_API_URL: ${{secrets.AUTH_API_URL}}
          HD_TOKEN_API_URL: ${{secrets.TOKEN_API_URL}}
          HD_FIREBASE_ADMIN_EMAIL: ${{secrets.FIREBASE_ADMIN_EMAIL}}
          HD_FIREBASE_ADMIN_PASSWORD: ${{secrets.FIREBASE_ADMIN_PASSWORD}}
          HD_GOOGLE_MAP_API_KEY: ${{secrets.GOOGLE_MAP_API_KEY}}