name: Update Firebase Rules

on:
  push:

jobs:
  update_firebase_rules:
    runs-on: ubuntu-latest

    env:
      FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
      DEV_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DEV_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "$DEV_GOOGLE_APPLICATION_CREDENTIALS" | base64 --decode > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Deploy Firebase Rules
        shell: bash
        run: |
          firebase deploy --project $FIREBASE_PROJECT --only firestore:rules

      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm $GOOGLE_APPLICATION_CREDENTIALS